# Generated by Django 3.2.22 on 2023-10-11 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_tool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('date_checked', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=30)),
                ('comments', models.TextField()),
                ('checked_by', models.CharField(max_length=50)),
                ('emission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_checks', to='monitoring_tool.emission')),
            ],
        ),
    ]
