# Generated by Django 3.2.22 on 2023-10-18 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_tool', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emissioncheck',
            name='title',
        ),
    ]
