# Generated by Django 3.2.22 on 2023-10-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_tool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emission',
            name='last_checked',
            field=models.DateField(auto_now=True),
        ),
    ]
