# Generated by Django 3.2.22 on 2023-10-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_tool', '0002_alter_emission_last_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='emission',
            name='close_or_delete_information',
            field=models.TextField(blank=True),
        ),
    ]
