# Generated by Django 3.2.22 on 2023-10-20 14:22

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_tool', '0003_rename_emission_emissioncheck_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='emission',
            name='emission_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='emission',
            name='status',
            field=models.IntegerField(choices=[(0, 'Open'), (1, 'Closed')], default=0),
        ),
    ]
