# Generated by Django 3.2.22 on 2023-10-24 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_tool', '0003_emission_close_or_delete_information'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emission',
            old_name='close_or_delete_information',
            new_name='close_out_comments',
        ),
    ]
