# Generated by Django 3.2.22 on 2023-10-13 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_tool', '0004_alter_emissioncheck_checked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emission',
            name='content',
        ),
    ]
