# Generated by Django 3.2.22 on 2023-10-29 01:31

import cloudinary.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_tool', '0007_alter_emission_emission_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emission',
            name='emission_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'tiff', 'heif'])]),
        ),
    ]
