# Generated by Django 3.2.22 on 2023-10-30 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_tool', '0012_emission_closed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='emission',
            name='close_out_date',
            field=models.DateTimeField(null=True),
        ),
    ]
