# Generated by Django 3.2.22 on 2023-10-31 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_tool', '0013_emission_close_out_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emission',
            name='close_out_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
