# Generated by Django 3.2.22 on 2023-11-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_tool', '0014_alter_emission_close_out_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emission',
            name='close_out_comments',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='emission',
            name='closed_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='emission',
            name='description',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='emission',
            name='title',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='emissioncheck',
            name='status',
            field=models.IntegerField(choices=[(1, 'No Emission Detected'), (2, 'Below Minimum Threshold'), (3, 'Above Minimum Threshold')], default=0),
        ),
    ]
