# Generated by Django 3.2.22 on 2023-11-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_tool', '0017_alter_emission_close_out_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissioncheck',
            name='edit_comments',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='emissioncheck',
            name='edit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emissioncheck',
            name='edited_by',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
