# Generated by Django 3.2.22 on 2023-11-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_tool', '0019_alter_emissioncheck_date_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emission',
            name='last_checked',
            field=models.DateField(),
        ),
    ]
