# Generated by Django 3.2.22 on 2023-11-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_tool', '0020_alter_emission_last_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emission',
            name='last_checked',
            field=models.DateField(blank=True, null=True),
        ),
    ]
