# Generated by Django 3.2.22 on 2023-12-04 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_tool', '0021_alter_emission_last_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emission',
            name='location',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='emission',
            name='title',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
