# Generated by Django 3.2.22 on 2023-12-04 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_tool', '0022_auto_20231204_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emission',
            name='title',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
